### ISSUE TITLE
explain why extended privileges (sudo, doas) are needed + describe upstream and version from shipped dependency

### ISSUE THREAD

**Issue by matu3ba** [tw4452852/zbpf#1]
Afaik, only (temporary) attaching stuff to the Kernel needs extended privileges, not building. I guess you are tracking a release of https://github.com/libbpf/libbpf ?

**Comment by tw4452852** [comment]
There are two things here that need root privileges:

- Structure definition during building time.
- Running unit tests.

**Comment by matu3ba** [comment]
Thanks, feel free to close then unless you think its worth to mention.

**Comment by tw4452852** [comment]
As https://github.com/tw4452852/zbpf/commit/bee06176592aef273207e892e307721931af4060 landed, we don't need root privilege to compile right now.
FYI.
